#! /bin/sh

set -e

PIDFILE=/var/run/sensortag.pid
DAEMON=/usr/share/qtsensortag-headless-1.0.0/sensorconsole

# start and stop the sensortag demo

test -x ${DAEMON} || exit 0

umask 022

. /etc/init.d/functions

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
    start)
        echo "Starting sensortag demo" "sensorconsole"
        if start-stop-daemon --start --quiet --oknodo --background  --make-pidfile --pidfile ${PIDFILE} --exec ${DAEMON} -- -b /usr/share/qtsensortag-headless-1.0.0/broker.json >>/var/log/sensortag.log 2>&1; then
            exit 0
        else
            exit 1
        fi
        ;;
    stop)
        echo "Stopping sensortag demo" "sensorconsole"
        if start-stop-daemon --stop --quiet --oknodo --pidfile ${PIDFILE}; then
            rm -f ${PIDFILE}
            exit 0
        else
            exit 1
        fi
        ;;


    reload|force-reload)
        if [ -f ${PIDFILE} ] ; then
            echo "Reloading configuration for sensortag"
            pid=`cat ${PIDFILE}`
            kill -HUP $pid
        else
            echo "sensortag does not seem to be running"
        fi
        ;;

    restart)
        echo "Restarting sensortag demo" "sensorconsole"
        if start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile ${PIDFILE}; then
            rm -f ${PIDFILE}
        fi
        if start-stop-daemon --start --quiet --oknodo --background --make-pidfile --pidfile ${PIDFILE} --exec ${DAEMON} -- >> /var/log/sensother 2>&1; then
            exit 0
        else
            exit 1
        fi
        ;;

    status)
        status ${DAEMON} && exit 0 || exit $?
        ;;

    *)
        echo "Usage: $0 {start|stop|reload|force-reload|restart|status}"
        exit 1
esac

exit 0
